source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!


target 'QuickVideoSwift' do
  
    
pod 'BFKit-Swift', '~> 3.1.2'
pod 'RxSwift'
pod 'RxCocoa'
pod 'SnapKit', '~> 4.0'

end
